[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pump = "BR1gGg7joMV6PxKMgsszrSydXJAPMyk1KQC7wtx8Vz7M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/sung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
