[toolchain]
fixed = "1.23.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
pump = "kC2US8dihwxp4MWXhTntSKAhQr6TBaLE8meED4mVjbh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/sung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/swap.ts"
